# Generated by Django 3.0 on 2021-09-11 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegedate',
            name='salary',
        ),
        migrations.AddField(
            model_name='collegedate',
            name='addmision_numbers',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
